FROM arm64v8/alpine:3.19
RUN echo "https://mirrors.ustc.edu.cn/alpine/v3.19/main/" > /etc/apk/repositories && \
    echo "https://mirrors.ustc.edu.cn/alpine/v3.19/community/" >> /etc/apk/repositories && \
    apk update && \
    apk add --no-cache ca-certificates && \
    rm -rf /var/cache/apk/*
