name: Build android opencl-llama(8gen1-3 ex)
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    name: Build static docker by ${{ github.actor }}
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CI: "false"
    steps:
    - uses: actions/checkout@v4
    - name: Prepare Configuration
      run: |
        echo "ENABLE_NETHUNTER=$(cat $CONFIG_ENV | grep -w "ENABLE_NETHUNTER" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        
    - name: Set swap to 10G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Setup build environment
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "DEVICE=$(echo ${{ env.KERNEL_CONFIG }} | sed 's!vendor/!!;s/_defconfig//;s/_user//;s/-perf//')" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt install -y curl vim git gcc unzip wget make crossbuild-essential-amd64 cmake ninja-build
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace
        cd $GITHUB_WORKSPACE/kernel_workspace
        wget https://dl.google.com/android/repository/android-ndk-r28-linux.zip
        unzip android-ndk-r28-linux.zip
        rm android-ndk-r28-linux.zip

  

    - name: build OpenCL
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        export ANDROID_NDK=$GITHUB_WORKSPACE/kernel_workspace/android-ndk-r28
        git clone https://github.com/KhronosGroup/OpenCL-Headers && \
        cd OpenCL-Headers && \
        cp -r CL $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/KhronosGroup/OpenCL-ICD-Loader && \
        cd OpenCL-ICD-Loader && \
        mkdir build_ndk && cd build_ndk && \
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
                -DOPENCL_ICD_LOADER_HEADERS_DIR=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include \
                -DANDROID_ABI=arm64-v8a \
                -DANDROID_PLATFORM=24 \
                -DANDROID_STL=c++_shared && \
        ninja && \
        cp libOpenCL.so $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android
        
    - name: build android llama.cpp with OPENCL
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        export PREFIX=/data/llama
        export ANDROID_NDK=$GITHUB_WORKSPACE/kernel_workspace/android-ndk-r28
        git clone https://github.com/ggml-org/llama.cpp.git llama
        cd llama
        cmake -G Ninja \
                 -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
                 -DANDROID_ABI=arm64-v8a \
                 -DCMAKE_BUILD_TYPE=Release \
                 -DANDROID_PLATFORM=android-28 \
                 -DCMAKE_PREFIX_PATH="/data/llama" \
                 -DBUILD_SHARED_LIBS=OFF \
                 -DGGML_OPENCL=ON \
                 -DLLAMA_CURL=OFF
          
        ninja   
        ninja install 
        
               
        
        
    - name: add llama tar
      run: |
        sudo bash -c 'cd /data && tar -czvf llama.tar.xz llama && cp llama.tar.xz /home/runner/work/builder-docker/builder-docker/kernel_workspace'
    

    - name: Upload llama
      uses: actions/upload-artifact@v4
      with:
        name: OpenCL-llama-android28-arm64
        path: kernel_workspace/llama.tar.xz

  
